### ISSUE TITLE
README - iOS framework section is not clear

### ISSUE THREAD

**Issue by amsdamsgram** [adjust/react_native_sdk#107]
Hi,

The iOS framework section is not clear.
https://github.com/adjust/react_native_sdk#ios-frameworks

The readme says:

> Select your project in the Project Navigator. In the left hand side of the main view, select your target. In the tab Build Phases, expand the group Link Binary with Libraries. On the bottom of that section click on the + button. Select the AdSupport.framework and click the Add button. Unless you are using tvOS, repeat the same steps to add the iAd.framework, CoreTelephony.framework, AppTrackingTransparency.framework and StoreKit.framework. Change the Status of both frameworks to Optional. Adjust SDK uses these frameworks with following purpose:

"Change the Status of both frameworks to Optional" but I am not sure which frameworks it is talking about.

Thank you for your help,

**Comment by lukvol** [comment]
I only have an idea for one of the two frameworks:
If you want to support older versions than iOS 14, you should set the state of the AppTrackingTransparency framework to "Optional" as otherwise, the app will crash on devices running on a version older than iOS 14 as it will not find the framework.
You can see the required version on the corresponding page from the Apple documentation:
- [AddSupport.framework](https://developer.apple.com/documentation/adsupport): iOS 6.0+
- [iAd.framework](https://developer.apple.com/documentation/iad): iOS 4.0+
- [CoreTelephony.framework](https://developer.apple.com/documentation/coretelephony): iOS 4.0+
- [AppTrackingTransparency.framework](https://developer.apple.com/documentation/apptrackingtransparency): iOS 14.0+
- [StoreKit.framework](https://developer.apple.com/documentation/storekit): iOS 3.0+

BTW: this means, that you need to use Xcode 12 (or use some [hack](https://stackoverflow.com/questions/63253750/how-do-i-build-submit-apps-build-with-ios-14-apis-using-xcode-11#comment111919014_63259605) to build your app).

**Comment by uerceg** [comment]
Hey guys. Sorry for a bit of delay in response. You're right, content sounds kinda confusing. It should pretty much say that absolutely every framework mentioned in `iOS Frameworks` section should be marked as `Optional`, since Adjust SDK doesn't have hard dependency to any of those. If they are present, we might use them for some features, but if not, things will still work without those features.

So feel free to mark them ALL as optional. We're gonna reword this in upcoming release stress this in less confusing way.

Cheers

**Comment by amsdamsgram** [comment]
Hi, thank you for your clear answer!

**Comment by pke** [comment]
It would be nice of you could specify for which feature exactly the frameworks are required to decide whether to include or omit them (bundle size, stability, bloat)

**Comment by Bardiamist** [comment]
@uerceg Is still required to link iOS frameworks manually for the best behaviour or will it be linked automatically?

**Comment by uerceg** [comment]
Hey @Bardiamist,

It is still required to link them manually. Technically, we could state these inside of our Podspec file to be automatically weekly linked, but taking the line of the less intrusive approach, we have things set in a way to give users a choice to add this if they are interested in doing so.

@pke Sorry for the delay in replying. We did [try to explain](https://github.com/adjust/react_native_sdk?tab=readme-ov-file#ios-frameworks) what is the purpose of adding each of these frameworks. They are not something that's vital for overall functionality of the SDK, but depending on whether you are interested in using certain of those features behind the scenes when it comes to attribution around your app, you might want (or not) to add frameworks that support those features. We unfortunately don't have the numbers that on how big of an impact adding those is to the size of the app bundle. When it comes to stability, all of those frameworks are made and provided by Apple, so they should probably as stable as they possibly could be.
