### ISSUE TITLE
Segment Adjust

### ISSUE THREAD

**Issue by Jparrgam** [adjust/react_native_sdk#128]
Hola a todos, estamos realizando pruebas del sdk de adjust con segment para el envio de eventos pero tenemos un problema no vemos reflejado un evento especifico en el dashboard de Adjust, me podrian ayudar por favor

**Comment by mauro90015** [comment]
Hello team! We are integrating with Adjust to have more clarity of our attribution windows as a business. We are doing the process through Segmente, however the “Revenue” event has not been possible to install it in the correct way. Last week we had a meeting with Felippe who has already passed the requirement for an internal tkt. Reviewing the implementation in detail, we were doing it well.

We look forward to your help as this event is the most important for our business.

I attach the photo of the event.
<img width="1275" alt="Captura de pantalla 2021-06-14 a las 9 24 27 a  m" src="https://user-images.githubusercontent.com/85886122/121908274-74e13400-ccf2-11eb-93f4-8b3f495feb0b.png">

**Comment by yagizoztol** [comment]
Hi @mauro90015, 
In order to investigate this issue better, could you please provide us a screenshot of how did you implemented the revenue tracking in the app and which app token-event tokens u used during the implementation ? 
moreover we also offer a debugging through verbose Loggins, please enable the verbose log level put your sdk in sandbox mode and trigger a test for this revenue event. you can also share the logs with us

**Comment by uerceg** [comment]
Also in order to speed up the support process, I'd advise to either contact your dedicated account manager (in case you have one) or send us email with information requested above to support@adjust.com.
