### ISSUE TITLE
Cannot read property ‘create' undefined 

### ISSUE THREAD

**Issue by francisconoj** [adjust/react_native_sdk#130]
Hello, I am trying to implement the React Native SDK but I am having issues. I am getting “Cannot read property ‘create’ of undefined. I have also been unable to check my verbose logs. Could you please help me understand what is missing? Thank you!

![image](https://user-images.githubusercontent.com/77400134/125116158-875c4c80-e0a9-11eb-86e1-6e3033222e03.png)

**Comment by uerceg** [comment]
Hi @francisconoj 

Are you using Expo framework maybe?

Cheers

**Comment by uerceg** [comment]
Hi @francisconoj 

Any update on this one?

Cheers

**Comment by francisconoj** [comment]
Hi @uerceg  yes, I'm using Expo

**Comment by uerceg** [comment]
In that case unfortunately you can just use Adjust SDK out of the box (yet). If you want to use it, you would need to eject your app so that our React Native SDK plugin would be able to be used in current state.

We do have plans to add proper support so that our SDK can be used in Expo apps without ejecting, but for the time being, ejecting is the only way to go.

I'm gonna close this one, but in case you have any further questions on this topic, feel free to ping.

Cheers
