### ISSUE TITLE
Could not compile build file. Error in SDK 27.0.3

### ISSUE THREAD

**Issue by Rehan-05** [adjust/react_native_sdk#143]
FAILURE: Build failed with an exception.

* Where:
Build file 'E:\Office\LOS\reaction-apps\android\app\build.gradle' line: 144

* What went wrong:
Could not compile build file 'E:\Office\LOS\reaction-apps\android\app\build.gradle'.
> startup failed:
  build file 'E:\Office\LOS\reaction-apps\android\app\build.gradle': 144: unexpected token: 3 @ line 144, column 31.
             targetSdkVersion 27.0.3
                                   ^

  1 error

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

=============================================================================
Android plugin version: 4.1.1
Gradle version: 6.7

Error in code=======>>>>>
defaultConfig {
        applicationId "com.landofsneakerproject"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
        vectorDrawables.useSupportLibrary = true

        **targetSdkVersion 27.0.3      // here is the issue**
    }

==============
![sdk](https://user-images.githubusercontent.com/72587992/131455898-a3cef582-069b-418a-835f-5be955fee48d.PNG)

**Comment by uerceg** [comment]
Hi @Rehan-05 

I am not sure this is related to Adjust SDK. SDK itself doesn't set any target SDK if you're already setting one in your app. As you can see in [SDK configuration](https://github.com/adjust/react_native_sdk/blob/master/android/build.gradle#L8), we're gonna take whatever your app is setting for this value and if nothing set, we're gonna default to 26. But error you're seeing says that there's some syntax error in your `build.gradle` file. Try simply setting target SDK to 27. So instead of:

```gradle
targetSdkVersion 27.0.3
```

just say:

```gradle
targetSdkVersion 27
```

If you check [official docs](https://developer.android.com/guide/topics/manifest/uses-sdk-element.html), `targetSdkVersion` should be an integer and I assume that's why you're getting this error.

**Comment by Rehan-05** [comment]
Thanks for your concern.
All the bugs were successfully resolved. 

The reason for these bugs that showed about are:

1). In the android Gradle files mistakenly add the wrong SDK version that was not installed in the project.
2). Two code lines were the same in the Gradle file.

That's it.

**Comment by Rehan-05** [comment]
Thanks for your concern.
All the bugs were successfully resolved. 

The reason for these bugs that showed about are:

1). In the android Gradle files mistakenly add the wrong SDK version that was not installed in the project.
2). Two code lines were the same in the Gradle file.
