### ISSUE TITLE
Where i can get PushToken

### ISSUE THREAD

**Issue by oleksiizhuk** [adjust/react_native_sdk#179]
Adjust.setPushToken(token) - there is a line where I have to put the token, but how or where to get it?

**Comment by uerceg** [comment]
Hi @oleksiizhuk,

Sorry for delay in replying. When it comes to push token, what our SDK expects is pretty much to get either APNs token (if your app is running on iOS) or FCM token (if your app is running on Android).

**Comment by tastydev** [comment]
@uerceg Hello, i don't want to create a new Issue about pushToken handing so i will ask my question here.

According to the docs the method mentioned above has to be set to track install/reinstal/uninstall. This is achieved by adjust sending Silent Push Notifications to the app. So i would like to ask if removing notification permissions in the OS settings will count as Uninstall. Because the backend won't be able to sent a silent message to the App. That would make it unreliable. Is this correct or do i not understand the API?

**Comment by uerceg** [comment]
Hi @tastydev,

In theory, it would not make it unreliable. Uninstall detection is as reliable as APNs/Firebase knowing whether app is installed on the device and providing this information back to party which pings them for sending of silent push notification as an answer to that request. Uninstall detection via silent push notifications does not really depend on delivery of silent push notification to the device itself. APNs / Firebase have ways to figure out whether app is present on the device or not. If it's not present, they will provide back the answer which indicates that. But if app is present on the device, they'll reply with certain status code which indicates that they will try to send this notification to end device. Whether this notification will be sent or not, depends on Firebase / APNs, but at that moment, we don't really care about what's gonna be the outcome of that.

But yes, obviously if you are not able to obtain push notifications token from your user, we will not be aware of what's going on for that app because APNs / FCM will not be aware either. But AFAIK, if you would subscribe your application for remote notifications, this is something which user is not opting out of when they are asked to allow notifications or not - that refers to standard (non-silent) push notifications.

**Comment by tastydev** [comment]
Thank you for this explanation it helped alot!
