### ISSUE TITLE
setDeferredDeeplinkCallbackListener callback function not working

### ISSUE THREAD

**Issue by mustafakameldev** [adjust/react_native_sdk#199]
I'm using version ^4.32.1

I'm trying to get url data such as CAMPAIGN or ADGROUP but the function never called

my code like this 
```
            const adjust = new AdjustConfig(APP_TOKEN,AdjustConfig.EnvironmentSandbox);
            adjust.setDeferredDeeplinkCallbackListener(function (deeplink) {
                console.log("Deferred deep link URL content: ", deeplink);
            });
           adjust.setShouldLaunchDeeplink(true);
           Adjust.create(adjust);
```

**Comment by xtealer** [comment]
Having same issue here with `^4.32.1`... did you solve it?

**Comment by tobiaseisenschenk** [comment]
I have the same issue for ^4.33.0 on iOS. It works however when using the LinkMe feature. So i guess there is something not working correctly when adjust matches the fingerprint?

**Comment by uerceg** [comment]
Hey guys, sorry for delay in replying. Triggering of the deferred callback should not be related to the fact whether someone is using LinkMe feature or not.

Deferred deep link will be delivered into the app (and subsequently into this callback in case you have implemented it) in case install gets attributed to the click on tracker URL which contains deep link info inside of it. In order to check this flow, you should make sure to track the install on our end. Try following these steps and see whether callback gets triggered:

1. Make sure that tracker URL you're testing with is properly formatted.
2. In case you are not using your test device ID as part of the tracker URL, make sure to have probabilistic matching enabled for the test tracking in the dashboard settings.
3. Uninstall your app from test device.
4. Forget your test device from our backend via testing console.
5. Click on a tracker URL from from some page you loaded in your test device browser.
6. Ignore the redirection to the store.
7. Install app on your test device and launch SDK (preferably in sandbox mode and with log level set to verbose so that you can see what's happening in the logs).
8. If all went well, you should see install being tracked + deferred deep link sent back to SDK + deferred deep linking callback you have defined being pinged by the SDK.

Let us know if you have any further questions on this topic.

**Comment by tobiaseisenschenk** [comment]
Hi @uerceg thanks for the suggestions!
I already did follow them mostly because I previously found some of your answers on Github. It would be great if we could update the `README` with these steps once we figure it out as this is Adjust specific and essential to implement it correctly.

1. Yes
2. I was not aware of the possibility to include the device id in the tracker URL, but I just now turned on probabilistic matching, because that is closer to the real-world scenario (again was not aware this is important - thank you)
3. Yes
4. On Device I have used Adjust Insights to make those IDs visible. On Android I can use the advertising ID as the testing console says, but on iOS I only have the IDFV, which is not found in the console and according to the docs should be different for my app anyways. IDFA is all zeros unfortunately.
I guess I have to fall back on the Simulator or log Adjusts attribution info separately?
5-7. Yes
8. Not there yet

**Comment by uerceg** [comment]
Thanks for the docs improvement suggestion. 👍 

2. Yeah, in theory if you know your test device advertising ID (for example), you can put `&idfa=...` or `&gps_adid=...` to tracker URL and matching should be done automatically based on that ID once SDK tracks an install with it.
4. 🤔 It's weird that you can't use IDFV to forget your device. What you can do is to obtain `adid` (Adjust ID) for your device and try that identifier in testing console to forget your device. You can find `adid` in verbose logs inside of the answer from backend to anything which you might track. For example, answer to event being tracked:
```
{"app_token":"2fm9gkqubvpc","adid":"588bf2f197e4913f203c7d4e8dfe77ab","timestamp":"2023-02-02T14:24:39.380Z+0000","message":"Event tracked 'g3mfiw'"}
```
8. I guess you meant that you're not there yet for 8 (not 5)?

Having in mind what you said here:

> On Android I can use the advertising ID as the testing console says

If you do this flow on Android platform, is the callback still not getting triggered? If not, can you run this test with SDK set to sandbox environment and log level set to verbose / omit any sensitive data from the logs & share the logs with us?

**Comment by tobiaseisenschenk** [comment]
Thanks for the insights @uerceg !

2. This does not work for me. Putting the `&idfa=...` does not record the install or at least I can't find the device via `IDFA` nor `IDFV`. The latter makes least sense because it differs by app vendor and therefore will be a different id between the Adjust Insights app and my own app.
3. Using the `adid` works for me and I obtain it as shown below:
```
Adjust.create(adjustConfig);
setTimeout(() => {
	Adjust.getAdid((adid: string) => {
	console.info(`Adjust Id: ${adid}`);
    });
}, 8000);
```
This solved the issue for me on Android and I can get the Adid on iOS Simulators, but when I do a release build and test it on my iOS Device it does not work. Obviously it is a bit cumbersome as well to wait for 8s, because there is no async interface to know when adjust recorded the installation, but my main issue is that I can not obtain the `adid` on iOS devices at all.

Am I missing something here? I did accept the tracking prompt in all scenarios.

**Comment by uerceg** [comment]
Hey @tobiaseisenschenk,

And sorry for a bit of delay in responding.

When it comes to `adid`, here's a theory on what's happening behind the scenes for a bit of a context. `adid` is short for `Adjust` identifier and it's a server side generated ID for the device. In order to get in possession of it, upon initial launch SDK needs to send install `session` package to backend and upon getting a response to it, `adid` will be part of that response. This is the moment in which SDK first becomes aware of this identifier.

I'd not say that you're missing anything, but instead you are probably unaware of what is happening under the hood in native SDKs when trying to obtain `adid`. As you can see in React Native, API looks like an async API and it needs to be like that due to the nature of communication between the React Native app and its plugins. However, if you'd check native implementation of `adid` getter methods in [iOS](https://github.com/adjust/ios_sdk/blob/master/Adjust/Adjust.h#L171) and [Android](https://github.com/adjust/android_sdk/blob/master/Adjust/sdk-core/src/main/java/com/adjust/sdk/Adjust.java#L341-L344), you'd see that they are effectively synchronous getter methods (historical reasons for this).

With this in mind, that means that in case you invoke `getAdid` method sooner than SDK gets in possession of `adid`, you'll get a `null` as return value. And this is what you're trying to work around with your arbitrary 8000 delay.

The place where you can obtain `adid` as soon as SDK obtains it from backend are [session tracking success / failure callbacks](https://github.com/adjust/react_native_sdk/blob/master/README.md#session-event-callbacks). One of these callbacks will get triggered as soon as SDK tracks first `session` package upon initial launch in the app. Session tracking sometimes can fail in case backend already knows about the device and in that case it would deliver `adid` of that known device to that callback as well. So implementing both ensures that you'll have all cases covered to try to obtain `adid` as soon as one of these callbacks get triggered for the first time upon first SDK launch in the app.

Design of this getter will be changed in SDK v5 which we expect to ship in 2023 to make it truly async by its nature so that you don't need to go around with these callbacks, but simply to wait for your callback method to be pinged once SDK gets in possession of this identifier.

Hopefully that answers your question. In case you have any further questions, feel free to ping.

**Comment by uerceg** [comment]
I will close this one for now, but in case you are still facing the issue and / or have any further questions down this road, feel free to comment / reopen. Cheers.
