### ISSUE TITLE
What coarse value are we supposed to send to Apple for SKAN 4.0?

### ISSUE THREAD

**Issue by amsdamsgram** [adjust/react_native_sdk#211]
Hi,

What are the coarse values that we are supposed to send using the Adjust SDK?

The [type definition](https://github.com/adjust/react_native_sdk/blob/55a10a89851bfa35f7c90b1df8568a73ebe2bab0/index.d.ts#L228) of the `updateConversionValueWithErrorCallback` method says `string` but in the [actual definition](https://github.com/adjust/react_native_sdk/blob/55a10a89851bfa35f7c90b1df8568a73ebe2bab0/ios/AdjustSdk.m#L487-L490) it is a `number` if I'm correct?

Also, it seems like the SDK doesn't provide Apple static values for [coarse values](https://developer.apple.com/documentation/storekit/skadnetwork/coarseconversionvalue).
What should we send? "high", "medium", "low" or 0 for high, 1 for medium and 2 for low?

Thanks!

**Comment by amsdamsgram** [comment]
Any update?

**Comment by uerceg** [comment]
Hi @amsdamsgram,

Sorry for delay in replying. Coarse values natively in Apple's iOS SDKs are predefined constants which our SDK will resolve to anything we get from React Native side. But ultimately, values of those string constants on native side are strings `"low", `"medium"` and `"high"`. So that's what we would expect clients to send us as value of the coarse value parameter.

I didn't manage to understand where did you see that coarse value is a number? From the part you linked, coarse value is of [NSString type](https://github.com/adjust/react_native_sdk/blob/55a10a89851bfa35f7c90b1df8568a73ebe2bab0/ios/AdjustSdk.m#L488).

**Comment by amsdamsgram** [comment]
Thank you for your answer @uerceg !

My bad, I looked at the codebase too quickly, you're right, it is a string everywhere.
