### ISSUE TITLE
setDeferredDeeplinkCallbackListener issue

### ISSUE THREAD

**Issue by NancyGarg98** [adjust/react_native_sdk#214]
Want to know if setDeferredDeeplinkCallbackListener has worked for anyone?

**Comment by uerceg** [comment]
Hi @NancyGarg98,

What exactly doesn't work for you when it comes to deferred deep link listener? Can you explain the scenario you are trying out and:

1. What is that is happening when you do the test?
2. What is that you were expecting to happen instead?

**Comment by NancyGarg98** [comment]
So I did the setup for adjust 
This is how it looks 

<img width="986" alt="image" src="https://github.com/adjust/react_native_sdk/assets/94895178/fa5d8b80-d7a8-4074-8a8e-fba77633c946">


For testing -
1. I have connected real device to run debug app
2. Clicked on the generated deeplink op phone->took me to appstore-> installed app on phone through xcode
3. On launch of app, ATTracking permission pop up came >clicked allowed
4. Adjust got initialised

But I was expecting that the link would come to the listener , but it didn't come

**Comment by uerceg** [comment]
Thank you for the explanation. 👍 Here is the list of things which you need to do in order to see this callback getting triggered:

1. Make sure that tracker URL you're testing with is properly formatted (you can share the test link here if you want, feel free to remove any sensitive data from it).
2. In case you are not using your test device ID as part of the tracker URL (which you are not in your example from above), make sure to have probabilistic matching enabled for the test tracking in the dashboard settings.
3. Uninstall your app from test device.
4. Forget your test device from our backend via testing console.
5. Click on a tracker URL from from some page you loaded in your test device browser.
6. Ignore the redirection to App Store.
7. Install app on your test device and launch SDK (preferably in sandbox mode and with log level set to verbose so that you can see what's happening in the logs).
8. If all went well, you should see install being tracked + deferred deep link sent back to SDK + deferred deep linking callback you have defined being pinged by the SDK.

In case you missed some of these steps down the testing road, feel free to retry with all these steps being covered and let us know if you're still facing the issues.

**Comment by NancyGarg98** [comment]
@uerceg 

link i am trying is of form-
{custom_domain_with_deeplink_endpoint}?adj_campaign={}&adj_adgroup={}&adj_creative={}&adj_t={}f&adj_deeplink={}&adj_fallback={}&linkme=1

Also , we are using univeral links
probabilistic modelling is enabled

Is it all good?

Rest of the steps are same, have tried it all!

**Comment by uerceg** [comment]
Is `{custom_domain_with_deeplink_endpoint}` part of your link the `https://xxx.adj.st/`? Also, can you maybe send over the Adjust SDK native verbose logs from this run just so that we can see closer what's happening with the SDK in this scenario? Of course, feel free to remove anything you think of as something not to share in public.

**Comment by NancyGarg98** [comment]
verbose logs are too long to share

**Comment by uerceg** [comment]
We don't need all the logs from the app, feel free just to look for those with `[Adjust]` tag in front, those are coming from our SDK and those are the only ones we need to check.

**Comment by NancyGarg98** [comment]
> We don't need all the logs from the app, feel free just to look for those with `[Adjust]` tag in front, those are coming from our SDK and those are the only ones we need to check.



here are the logs - https://docs.google.com/document/d/1BhpBp-0nLEL1XFSQ4ahUn7R7IXdgmY6dmmV54WaVDNk/edit?usp=sharing

**Comment by uerceg** [comment]
Thanks for sharing the logs. From what I can see, it seems like you are using signature plugin as part of your app. In that case, you should check the testing guide from signature plugin docs in order to see your test device's install being properly attributed to the click you're making as part of this test.

In case you don't have the guide on your end and need an assistance about this, feel free to fire an email to support@adjust.com and reference this GitHub issue in there.

**Comment by NancyGarg98** [comment]
It was the signature issue!

You cannot test this in simulator if you have signature implementation, launching app from xcode doesnt count as valid activity, tried it from testflight, and it worked.

**Comment by AppalaNaidu01** [comment]
@NancyGarg98  can you please confirm do we need add [these](https://help.adjust.com/en/article/get-started-ios-sdk#add-ios-frameworks) frameworks in XCode to listen the deferred deep link?

https://help.adjust.com/en/article/get-started-ios-sdk#add-ios-frameworks
