### ISSUE TITLE
Remove iAd framework attribution and use Apple Ads Attribution API

### ISSUE THREAD

**Issue by numandev1** [adjust/react_native_sdk#218]
we received this email from Apple
```
Hello,

We're reaching out because at least one of the apps connected to your account is still making iAd framework attribution requests.

Earlier this year, we announced that the iAd framework no longer attributes downloads from Apple Search Ads campaigns and that apps should be updated to use the Apple Ads Attribution API instead. This API provides an attribution signal for all downloads originating from devices using iOS 14.3 and later.

Within the next two years, the iAd framework will be completely removed from iOS. When that happens, any app that contains iAd framework code, including from third-party SDKs, will no longer launch on iPhone and iPad. We encourage you to remove the iAd framework from your app as soon as possible. If you're using a third-party SDK, check with your provider to confirm that the SDK doesn't include the framework. If it does, you can ask your provider to remove it.

Learn more about the Apple Ads Attribution API 
If you have questions, feel free to contact us.
```
so We need to remove iAd framework attribution from our app and use Apple Ads Attribution API
is there any plan to use `Apple Ads Attribution API`

**Comment by uerceg** [comment]
Hello @numandev1,

Adjust native iOS SDK as of [v4.33.4](https://github.com/adjust/ios_sdk/releases/tag/v4.33.4) is not trying to talk to `iAd.framework` at all. Translated to React Native SDK, that means that as of the [v4.35.0](https://github.com/adjust/react_native_sdk/releases/tag/v4.35.0), React Native SDK is also not doing anything related to `iAd.framework`. Also, thank you for asking this question, I just noticed that our README is still advising that `iAd.framework` should be weakly linked - we will remove that soon.

But as far as Adjust is concerned, we don't need `iAd.framework` to be present in your app at all and you can freely remove it from your app.

As far as `AdServices.framework` is concerned (Apple Ads Attribution API), Adjust React Native SDK is supporting this as of [v4.26.0](https://github.com/adjust/react_native_sdk/releases/tag/v4.26.0) and in order to allow our SDK to make use of it, you just need to weakly link that framework to your app (like README suggests).

In case you have any further questions, feel free to ping.

**Comment by numandev1** [comment]
@uerceg thanks for your quick answer, let me remove `iAd.framework` and use `AdServices.framework` and let you know

**Comment by marlonfrr** [comment]
@numandev1 We ran into the same problem, should I just remove iAd.framework from "Link Binary With Libraries" Build Phases tab? That's it? Thank you!

**Comment by numandev1** [comment]
@marlonfrr yes, you just need to remove it, and make you if you have AdServices.framework or not, if not you then you should add it

**Comment by uerceg** [comment]
And I would advise you to double-check if post removing it and rebuilding your iOS Xcode project from React Native if the `iAd.framework` hasn't "returned" back to the project. Because if it's back, then some of the plugins might still be automatically adding it.

**Comment by marlonfrr** [comment]
Thanks!
