### ISSUE TITLE
Adjust - NoClassDefFoundError com.facebook.FacebookSdk with 'com.google.android.gms:play-services-analytics:9.8.0'

### ISSUE THREAD

**Issue by vasiliy-sarzhynskyi** [adjust/react_native_sdk#4]
Hi team,

We integrated our react-native application (for Android and iOS) with Facebook SDK and Adjust.
Integration with Adjust was done according to instruction from https://github.com/adjust/react_native_sdk.

After adding the following line into build.gradle: 
<code>compile 'com.google.android.gms:play-services-analytics:9.8.0'</code>

application on Android 4.0 - 4.4 started fails with the following exception: 
**Caused by java.lang.NoClassDefFoundError
com.facebook.FacebookSdk.<clinit> (FacebookSdk.java:83)**

meanwhile Android 5.0 and higher versions works fine.
Without the line above app works fine for all Android versions. Seems that Adjust also track custom events without 'play-services-analytics'.

Do you have any ideas why exception is thrown? And if we just remove  'play-services-analytics', will Adjust work appropriately (for tracking custom events)?

App has the following RN dependencies:
  - "react": "15.4.1",
  - "react-native": "0.39.2",
  - "react-native-adjust": "4.10.0"

If you need any additional information, please let me know.
Thanks in advance

Best regards,
Vasiliy

**Comment by uerceg** [comment]
Hi @vasiliy-sarzhynskyi 

And thanks for reporting this. Interesting. Can I ask you to try running your app on your Android device without this Google Play Services dependency line in the sandbox environment and log level set to verbose, track one event and paste me the logs you're seeing in the LogCat output with the tag `Adjust`? Also, for this test case, add `ACCESS_WIFI_STATE` permission to your Android manifest file.

Feel free to hide all the sensitive information from the log (app/event token and what ever you think of as something that you shouldn't share in here).

I would like to see if maybe you have Google Play Services dependency added to your app from some other place (although I don't give it a big odds, but just to double check).

Events are going to be tracked even w/o this dependency added to your app, that is correct. Everything works normally, it's just that without this dependency for tracking purposes instead of using Google Play Services advertising identifier (`gps_adid` parameter in the adjust verbose logs) which is pretty "constant" thing on the user's device, we are falling back to some MAC parameters for which we need the permission which I asked you to add above to this test case. Even w/o GPS dependency, matching the install with the click works well, it's just that apps that are released to the Google Play Store should use Google Play Services advertising identifier and also, lots of networks and other parties from the ecosystem ofter require the value of `gps_adid` parameter for bunch of use cases on their side. That's why it is useful to have this added to your app.

Cheers

**Comment by vasiliy-sarzhynskyi** [comment]
Hi @uerceg 

Thanks for your response and explanation. 

I tried to run our application without Adjust integration, and included Facebook SDK and play-services-analytics into grandle. Still received NoClassDefFoundError com.facebook.FacebookSdk for Android 4.*. So this fact means that the problem related to Facebook and not to Adjust =)

Also launched app with Adjust verbose log mode, please check attached file
[Adjust_log.txt](https://github.com/adjust/react_native_sdk/files/706265/Adjust_log.txt)

As we don't need 'play-services-analytics' now, just removed it from gradle.
Reported issue is not related to Adjust, so just close it.
Thanks

**Comment by uerceg** [comment]
Log seems just fine. gps_adid is there, so from that point of view, all good as far as our SDK intrgration is concerned.
