### ISSUE TITLE
SDK won't send sdk_click for install

### ISSUE THREAD

**Issue by ArmanAjdani** [adjust/react_native_sdk#62]
Hi, I added adjust sdk to my sample app , but the sdk_click request won't send from my app however , session and attribution requests are geting send:

```
export default class App extends Component{

	_onPress() {
		var adjustEvent = new AdjustEvent("03v1w4");
		Adjust.trackEvent(adjustEvent);
		Alert.alert("OK");
	 }
	componentWillMount(){
		var adjustConfig = new AdjustConfig("bwyeo7y07nlb", AdjustConfig.EnvironmentProduction);
		Adjust.create(adjustConfig);
	}

	componentWillUnmount() {
		Adjust.componentWillUnmount();
	}
}
```

This is my App.js file , Is this anything wrong? (In documntiation mentioned that put this in index.android.js but in newer version of react native index.android.js is deleted)

**Comment by ArmanAjdani** [comment]
any clue for this problem?

**Comment by uerceg** [comment]
Hi @ArmanAjdani 

Sorry for a bit delayed answer. `sdk_click` is something which SDK sends when ever it figures out that potential source of reattribution might be coming from "outside" (meaning that SDK knows that backend is not aware of it). It's not necessarily something which must follow an install. Although in case of Android platform, it should be there since SDK behaves in a way that it asks Google referrer API for referrer and once we get it, we send it as part of `sdk_click` package.

If you are running this test on Android platform, would be good if you can test it in sandbox mode with verbose log level set and then give us the logs to see what's up in there.

**Comment by uerceg** [comment]
in case there's a need for it, feel free to reopen the issue. Cheers.

**Comment by sohail-dragon** [comment]
I still have this issue today. Using `4.17.0`.

I see the tracker being detected in the logs (`source: deeplink`) but still don't receive any new re-attribution event. I can provide any further logs if you need.

**Comment by uerceg** [comment]
Hi @sohail-dragon 

Would be great if you can provide us logs and explain:

1. How does SDK integration look like in your app?
2. How does the test scenario look like and what are you expecting to happen?
3. What is happening instead?

Cheers

**Comment by sohail-dragon** [comment]
Wow, thanks for you prompt reply.

1. We're using react-native `0.61.5` with `react-native-adjust` and have setup everything like explained in the readme. In fact we've had it well integrated since almost a year now. We're using a differed deep link handler to handle the deeplink embedded in the adjust link and calling `Adjust.appWillOpenUrl(url)` when thee link opens.
2. We're not currently in the app store so I need to test the reattribution by removing the the idfa from the testing console each time. Ideally we're expecting the app to launch and attribute to the primary tracker in the URL. If the app is already attributed, we want to force re-attribute it via the the deeplink. We also have a handler to independently trigger the deeplink and call `Adjust.appWillOpenUrl(url)` but there's no re-attribution event in the `setAttributionCallbackListener` callback.
3. The attribution isn't changing in both cases. Neither on click of the adjust link (and triggering the deferred deeplink) nor when the deeplink is called directly (app pre-installed)

**Comment by uerceg** [comment]
So if I understood properly from 3, you are not seeing even initial attribution being assigned to desired one even if you test deferred deep link scenario (next to standard deep link scenario).

This is now just for the record, to be aware of few things which might be useful on the road.

**When testing you should perform following steps for deferred deep linking scenario**:
- Uninstall app from your test device.
- Forget your device in testing console.
- Click on tracker URL.
- Install app on your test device (debug build is perfectly fine).

**Tings to be aware of when running test for deferred deep linking case**:
- Tracker URL should be properly formatted (best address to double check this is support team).
- Next to proper formatting of tracker URL when it comes to what needs to be URL encoded and what not, important thing to pay attention to is tracker itself which you're using inside of it and which you have created in the dashboard.
- If your tracker URL doesn't contain your test device advertising ID (**&idfa=whatever** for iOS or &**gps_adid=whatever** for Android), then fingerprinting must be performed in order for this click to get attributed to later install incoming from your device.
- Fingerprinting for newly created trackers is OFF by default once they are created in dashboard. So if you are not using your device ID in tracker URL, you need to go to dashboard and enable fingerprinting for clicks for your test tracker in attribution setting for the tracker.
- If you don't want to mess around with these settings for tracker, then you can simply put your device's advertising ID in tracker URL and matching of install and click should be pretty straight forward.

**When testing direct deep linking scenario**:
- It is important to have call to `appWillOpenUrl` method set in place where deep link which has opened your app gets delivered into the app. This seems to me that has been done in your app from what I've understood (if this works can be checked in verbose SDK logs when deep link opens your app -> if `sdk_click` package with `source=deeplink` parameter gets sent by SDK, that's it).
- In this scenario install will originally be attributed to whatever (organic tracker or something else if you clicked on some tracker URL prior to install). Information about deep link which `sdk_click` package sends to backend is something which potentially can change the original attribution.
- But this is now again place where support team is best address to double check if all conditions for this to happen are met. There are things such as inactivity window which needs to be set so that `sdk_click` with deep link doesn't get ignored by backend (inactivity windows is like interval in which reattribution can't take place) and maybe there are some other things which need to be respected in order for this test scenario to succeed, but like said - support team is definitely more knowledgable on this topic.

In case you have any further questions, feel free to ping.

**Comment by sohail-dragon** [comment]
Hey thanks once again. It's seems the inactivity window is the issue. I guess we'd like to force the reattribution irrespective of the inactivity window. I'll contact the support team for this to see if it's even possible. Thanks for all your help.
