### ISSUE TITLE
Feature request: bridge the Adjust.convertUniversalLink method

### ISSUE THREAD

**Issue by tootsweet** [adjust/react_native_sdk#75]
Hello,

Under iOS, when launching a universal link while the app is closed, the native continueUserActivity() method is called before the JS bundle is loaded. Therefore, the React Native's linking listener is never fired (Linking.addEventListener).

The initial URL can be read with Linking.getInitialURL, but in the case of universal links, the raw URL needs further processing by the Adjust SDK.

The only way (without duplicating code) to do that is to bridge the Adjust SDK's convertUniversalLink() method in order to make it accessible JS-side.

I can do it if you guys accept PRs.

Thanks,
Elyes

**Comment by uerceg** [comment]
Hi @tootsweet 

Of course we accept PRs, as a matter a fact, we are pretty happy when we see someone outside of @adjust contributing to our repos.

Conversion method you're mentioning was added as a helper method a while ago in native iOS SDK to serve as a convertor of universal links into scheme based links since when Apple started to force people to use universal links, lots of people still wanted to see Adjust links in scheme based style, so that they would not need to change their parsing logic which they already had in place for their apps.

Wanted to ask you what would existence of this method bring to you in your case? In theory, all the information you put into universal link is there in it (when you obtain it with Linking component), so you might as well do the parsing of it directly.

**Comment by tootsweet** [comment]
Hello @uerceg,


I just don't wanna duplicate code (native + JS).
I'll do the PR.


Regards,
Elyes

**Comment by tootsweet** [comment]
It's done.

Elyes
