### ISSUE TITLE
Which version of Adjust Native SDK?

### ISSUE THREAD

**Issue by dguillamot** [adjust/react_native_sdk#85]
Hello, 

It's unclear from the README which version of the Adjust native library is used with this package. 

Adjust SDK version 2 (V2) is being sunset on May 15th. So would like confirmation that react-native-sdk is including a more recent version if possible. 

Thanks a lot.

**Comment by uerceg** [comment]
Hi @dguillamot 

You can usually always see this information from [CHANGELOG](https://github.com/adjust/react_native_sdk/blob/master/CHANGELOG.md) since in there we always add **Native SDKs* section with each update.

Also regarding that deprecation, no need to worry, React Native SDK was built way after native Android SDK v2, so it never contained it. I'd say you're pretty on a safe side when it comes to this upcoming native deprecation with React Native SDK.

In case you have any further questions, feel free to ping.

Cheers
