### ISSUE TITLE
Give duplicate files error when running as Android app

### ISSUE THREAD

**Issue by CrazzzyDev** [adjust/react_native_sdk#88]
Duplicate class com.adjust.sdk.ActivityHandler found in modules adjust-android-4.21.2.jar (com.adjust.sdk:adjust-android:4.21.2) and adjust-android.jar (adjust-android.jar)
Duplicate class com.adjust.sdk.ActivityHandler$1 found in modules adjust-android-4.21.2.jar (com.adjust.sdk:adjust-android:4.21.2) and adjust-android.jar (adjust-android.jar)
Duplicate class com.adjust.sdk.ActivityHandler$10 found in modules adjust-android-4.21.2.jar (com.adjust.sdk:adjust-android:4.21.2) and adjust-android.jar (adjust-android.jar)
Duplicate class com.adjust.sdk.ActivityHandler$11 found in modules adjust-android-4.21.2.jar (com.adjust.sdk:adjust-android:4.21.2) and adjust-android.jar (adjust-android.jar)
Duplicate class com.adjust.sdk.ActivityHandler$12 found in modules adjust-android-4.21.2.jar (com.adjust.sdk:adjust-android:4.21.2) and adjust-android.jar (adjust-android.jar)
Duplicate class com.adjust.sdk.ActivityHandler$13 found in modules adjust-android-4.21.2.jar (com.adjust.sdk:adjust-android:4.21.2) and adjust-android.jar (adjust-android.jar)
Duplicate class com.adjust.sdk.ActivityHandler$14 found in modules adjust-android-4.21.2.jar (com.adjust.sdk:adjust-android:4.21.2) and adjust-android.jar (adjust-android.jar)
Duplicate class com.adjust.sdk.ActivityHandler$15 found in modules adjust-android-4.21.2.jar (com.adjust.sdk:adjust-android:4.21.2) and adjust-android.jar (adjust-android.jar)
....

Continue with above error for several files.

**Comment by uerceg** [comment]
Hi @CrazzzyDev 

Not sure how, but somehow you ended up having `adjust-android.jar` and `adjust-android-4.21.2.jar` inside of you Android app. `adjust-android-4.21.2.jar` shouldn't in theory be there since native Android SDK inside of our React Native plugin is added with `adjust-android.jar` name (you can see that in our repo in [here](https://github.com/adjust/react_native_sdk/tree/master/android/libs)).

I'd say feel free to remove `adjust-android-4.21.2.jar` and hopefully it should do the trick.

Cheers

**Comment by CrazzzyDev** [comment]
@uerceg Thanks for the answer. 

It fixed for me now. 
My Solution:
I have removed dependency of adust sdk from build.gradle file, still it working!! 
Seems it found the adjust sdk by other way, like as dependency of other library.
