### ISSUE TITLE
Adjust.getAdid returns null specifically on first install and start of app

### ISSUE THREAD

**Issue by CrazzzyDev** [adjust/react_native_sdk#90]
I have tries to call getAdid function on constructor and after some delay as well. but it returns null.
Adjust.getAdid((adid) => {
      console.log('getAdid: ' + adid);
    });

Please help on when to call it to make sure, it returns adid?

**Comment by uerceg** [comment]
Hi @CrazzzyDev 

That's probably expected. Pay attention to [note](https://github.com/adjust/react_native_sdk#di-adid) written in chapter about this getter in README. `adid` is parameter which is not generated by SDK, but rather our backend. And upon first SDK launch ever, SDK doesn't have it, but rather needs to perform some kind of communication with our backend in order to get it. Until that happens, in SDK this value is `null`.

From SDK point of view, this getter should start to return `adid` value to caller maybe second after `Adjust.create(adjustConfig);` is called if internet connectivity is present and SDK managed to track install session.

**Comment by ugi** [comment]
If you're still facing issues with this, feel free to comment/reopen.

**Comment by michaelknoch** [comment]
How can we know on the client that the communication between adjust SDK and backend has been established? Because `Adjust.getAdid(cb)` takes a callback, I was expecting that the callback gets called once the adid is available. It seems that the cb gets invoked with null instantly. Waiting an arbitrary amount of time and then running `Adjust.getAdid(cb)` would be a workaround but it doesn't feel solid @uerceg

**Comment by numandev1** [comment]
@uerceg is there any way to know if the backend has sent aid to our app or not, i think, callback should trigger after getting adid value from backend

**Comment by numandev1** [comment]
@michaelknoch you can use this listener `setSessionTrackingSucceededCallbackListener` it will trigger at first install

```
 adjustConfig.setSessionTrackingSucceededCallbackListener(function (
      sessionSuccess,
    ) {
       console.log(sessionSuccess.adid)
    });
    Adjust.create(adjustConfig);
```
