### ISSUE TITLE
[Question] Using adjust with wix/react-native-navigation

### ISSUE THREAD

**Issue by mihaerzen** [adjust/react_native_sdk#95]
Hi!

We are gonna add adjust tracking to our react native application. We are using wix/react-native-navigation library for our app navigation.

In the documentation, you state the initialization should be done in the `App.js` file, however, react-native-navigation doesn't really have a global app wrapper (or I'm not aware of it).

Where would you recommend we put the `Adjust.create` and `Adjust.componentWillUnmount` methods?

I can see putting the `Adjust.create` method inside the `registerAppLaunchedListener` method but I'm unsure (if even needed) where to put the `Adjust.componentWillUnmount`.

Thank you for your response!

**Comment by uerceg** [comment]
Hi @mihaerzen 

As far as initialisation of SDK is concerned, general rule of thumb is simply to try to do it ASAP in your app. Example we made with `App.js` was just an example how this might be done, not mandatory to be done in that place if you don't have it. So as soon as you can, would be great.

And regarding `componentWillUnmount` method -> this method cleans up callback methods from the app set on Adjust SDK for various things (you can check this in README, one can set callback for getting attribution, event/session tracking success/failure and deferred deep link information) and sometimes people tend to rerun SDK initialisation code multiple times so addition of this method in our API and advice where to call it was best effort to clean up these callbacks in order not to have them defined multiple times since SDK remembers only one. I'd say that if you make sure that SDK initialisation (`Adjust.create`) is called just once, there's no need for you to invoke unmount method.

In case you have any further questions, feel free to ping.

Cheers

**Comment by mihaerzen** [comment]
Thank you for your response @uerceg! It makes sense what you wrote.

As the method is called `componentWillUnmount` it implies it should be used in the `componentWillUnmount` react lifecycle hook but actually it's just a cleanup method. Maybe one proposal would be to re-name it to something which reflects that better. Maybe `Adjust.destroy()`?

Again thank you for a fast reply, greatly appreciated!

**Comment by uerceg** [comment]
@mihaerzen Yeah, I'd say that definitely you're right. I guess reasoning back in the days was to maybe with name give "a hint" where would be appropriate place for method to be called in the RN app itself, but obviously for your use case, it can be misguiding. By EOY we are most probably going to release next major SDK update where we have a chance to do API cleanup and this would definitely be one of the things on the list for React Native SDK.

Thanks for the suggestion! Will close this one for now, but in case you have any further questions or need assistance, feel free to comment/reopen.

Cheers!
